### ISSUE TITLE
Understroke on mid tone

### ISSUE THREAD

**Issue by oadams** [alexis-michaud/na-data#1]
```
W id="F4_TONETUTORIAL_PART1_008"                                              
bv˧̩ɻ˧̍-ʂo˧~ʂo˥
```

Is `v˧̩` meant to be `v̩˧`? My Na parser fell down on this. This same sentence also has an overstroke on the second mid tone.

**Comment by alexis-michaud** [comment]
2018-02-24 5:15 GMT+01:00 Oliver Adams <notifications@github.com>:

> bv˧̩ɻ˧̍-ʂo˧~ʂo˥
>
> Is v˧̩ meant to be v̩˧?
>
Absolutely!! Well spotted.

> My Na parser fell down on this.
>
Good job from the Na parser!
<W id="F4_TONETUTORIAL_PART1_008">
<FORM kindOf="phono">bv̩˧ɻ̍˧-ʂo˧~ʂo˥</FORM>

(There's a weak spot in my 'workflow' (that's a big word; maybe just refer
it as 'working habits'): I do manual 'sanity checks' on XML files but
sometimes forget to include some of the files.)

It's now corrected and committed to the *na-corpus* repository.

Many thanks,

Alexis

-- 
Alexis Michaud, CNRS researcher (Chargé de recherche)
LACITO <http://lacito.vjf.cnrs.fr/membres/michaud_en.htm>, centre
André-Georges Haudricourt
Adjunct member of *Laboratoire de Phonétique et Phonologie*, Paris
<http://lpp.in2p3.fr/>
Language documentation that I collect is available online in the Pangloss
Collection <http://lacito.vjf.cnrs.fr/pangloss/index_en.html>

**Comment by oadams** [comment]
My pleasure!
